# Generated by Django 5.1.4 on 2025-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='duration',
            field=models.CharField(default='2 hour', max_length=20),
        ),
    ]
