# Generated by Django 5.1.4 on 2025-01-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_timeslot_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.classroom')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.timeslot')),
            ],
        ),
    ]
