# Generated by Django 5.1.4 on 2025-01-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classroomavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='semester',
        ),
    ]
