# Generated by Django 5.1.4 on 2025-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_unit_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='online_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='physical_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
