# Generated by Django 5.1.4 on 2025-01-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_unit_online_hours_alter_unit_physical_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], max_length=10)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.classroom')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='school.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
