# Generated by Django 5.1.4 on 2025-01-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_timeslot_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomavailability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
