# Generated by Django 5.1.4 on 2025-01-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_classroom_is_available_delete_classroomavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='lecturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='classroom',
            field=models.CharField(default='Online', max_length=100),
        ),
    ]
