# Generated by Django 5.1.4 on 2025-01-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_classtimetable_duration_classtimetable_lecturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='lecturer',
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
