# Generated by Django 5.1.4 on 2025-01-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_classtimetable_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='status',
            field=models.CharField(choices=[('physical', 'Physical'), ('online - Zoom', 'Online - Zoom')], max_length=20),
        ),
    ]
