# Generated by Django 5.1.4 on 2025-01-25 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_classtimetable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='classtimetable',
            name='duration',
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.CreateModel(
            name='ClassroomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.classroom')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.timeslot')),
            ],
        ),
    ]
